/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts.index'
import { Route as ReceiptsIdRouteImport } from './routes/receipts.$id'
import { Route as ReceiptsNewRouteImport } from './routes/receipts.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceiptsRoute,
} as any)
const ReceiptsIdRoute = ReceiptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReceiptsRoute,
} as any)
const ReceiptsNewRoute = ReceiptsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReceiptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/receipts': typeof ReceiptsRouteWithChildren
  '/receipts/$id': typeof ReceiptsIdRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/receipts/': typeof ReceiptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/receipts': typeof ReceiptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/receipts': typeof ReceiptsRouteWithChildren
  '/receipts/$id': typeof ReceiptsIdRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/receipts/': typeof ReceiptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/history'
    | '/inventory'
    | '/receipts'
    | '/receipts/$id'
    | '/receipts/new'
    | '/receipts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/history'
    | '/inventory'
    | '/receipts/$id'
    | '/receipts/new'
    | '/receipts'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/history'
    | '/inventory'
    | '/receipts'
    | '/receipts/$id'
    | '/receipts/new'
    | '/receipts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  HistoryRoute: typeof HistoryRoute
  InventoryRoute: typeof InventoryRoute
  ReceiptsRoute: typeof ReceiptsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof ReceiptsRoute
    }
    '/receipts/$id': {
      id: '/receipts/$id'
      path: '/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof ReceiptsIdRouteImport
      parentRoute: typeof ReceiptsRoute
    }
    '/receipts/new': {
      id: '/receipts/new'
      path: '/new'
      fullPath: '/receipts/new'
      preLoaderRoute: typeof ReceiptsNewRouteImport
      parentRoute: typeof ReceiptsRoute
    }
  }
}

interface ReceiptsRouteChildren {
  ReceiptsIdRoute: typeof ReceiptsIdRoute
  ReceiptsNewRoute: typeof ReceiptsNewRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
}

const ReceiptsRouteChildren: ReceiptsRouteChildren = {
  ReceiptsIdRoute: ReceiptsIdRoute,
  ReceiptsNewRoute: ReceiptsNewRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
}

const ReceiptsRouteWithChildren = ReceiptsRoute._addFileChildren(
  ReceiptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  HistoryRoute: HistoryRoute,
  InventoryRoute: InventoryRoute,
  ReceiptsRoute: ReceiptsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
